services:

  postgres:
    image: postgis/postgis:17-3.5
    container_name: parqueo-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: parqueo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data/01-estructura.sql:/docker-entrypoint-initdb.d/01-estructura.sql
      - ./data/02-insercion.sql:/docker-entrypoint-initdb.d/02-insercion.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d parqueo"]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres

  api:
    build: ./backend
    container_name: parqueo-api
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://admin:admin123@postgres:5432/parqueo
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./shared:/shared

  frontend:
    build: ./frontend
    container_name: parqueo-front
    ports:
      - "8080:80"
    depends_on:
      - api

  # Apache Airflow
  airflow:
    image: apache/airflow:2.8.1-python3.11
    container_name: parqueo-airflow
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://admin:admin123@postgres:5432/parqueo
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__WEBSERVER__SECRET_KEY=tu_clave_secreta_123
    ports:
      - "8081:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./shared:/shared
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      bash -c "
      airflow db init &&
      airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com || true &&
      airflow webserver & airflow scheduler
      "

  # Apache Spark
  spark:
    image: apache/spark:3.5.0
    container_name: parqueo-spark
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
    ports:
      - "8082:8080"
      - "7077:7077"
    volumes:
      - ./spark/jobs:/opt/spark/jobs
      - ./shared:/shared

volumes:
  postgres_data: